### ISSUE TITLE
Avoid per-query code duplication in SchemeRunner

### ISSUE THREAD

**Issue by zivnevo** [IBM/network-config-analyzer#104]
Currently, the same code for running a query is pretty much duplicated for each query.
Maybe a generator can replace parts of the for loops in each query

**Comment by shireenf-ibm** [comment]
Hi @zivnevo 
while unifying the queries functions , I realized an issue with the InterferesQuery.

When calling it from the CLExecute.py , the base_np_config is passed to it as its 2nd parameter as followed : 
`        full_result = NetworkConfigQuery.InterferesQuery(exclusive_network_policy, base_np_config).exec()
`

while in SchemeRunner.py the base_config is passed as its first param as following (def _run_interferes) : 
`            full_result = InterferesQuery(base_config, self._get_config(config), output_configuration).exec()
`

In my code i will use a one method for both command-line and scheme-runner calls as well the same call will be used for other queries (permits, forbids, containment ..) and since the other queries send the base config as the 2nd parameter , I prefer that too.. as follows: 
`        full_result = getattr(NetworkConfigQuery, query_type)(config, base_config, self.output_configuration).exec()
`
To solve the conflicts that are caused I think of 2 options:
-> make changes in the InterferesQuery.exec() 
-> or make changes to the "scheme" tests that may fail if we send the base config as the 2nd parameter 

would like to know your opinion in this

**Comment by zivnevo** [comment]
> 

I think we can flip the parameters in the call from `CLExecute.py` (and fix relevant tests). This means we'll be checking if the given network-config interferes with the base network-config. It actually makes more sense.
Just make sure to update the documentation (in code and in `README.md`).
