### ISSUE TITLE
activate tests performance tracking in the current workflow

### ISSUE THREAD

**Issue by adisos** [IBM/network-config-analyzer#134]
Activate the new flag for performance comparison in the run_tests script (on the workflow .github/workflows/test-push.yml  , update run_all_tests with type general to run with flag --check_run_time).
Use workflow artifacts to save the runtime comparison results.

**Comment by adisos** [comment]
Based on the discussion on https://github.com/IBM/network-config-analyzer/pull/154:

- [ ] Add some mechanism to enable auto-update expected run-time when new tests are added or existing tests are modified.

**Comment by shireenf-ibm** [comment]
>     * [ ]  Is it possible to add some warning if there are gaps?

Hi,
As I saw, a warning will be printed to the log as an artifact creation is printing.
But ,although we don't have any performance issues currently and max factor (for tests other than git_resources, which I raised its expected runtime) was 2.3. 
In future we'll not be able to tell if there are performance issues unless we check manually the existence of the "failed_runtime_check" artifact, a thing that may be forgotten.
So for example, shouldn't we increase the runtime_check factor up to 2.5 or 3 (instead of 2 ) 
and then to "stop/fail" the workflow run in case the failed_runtime_check artifact is created?

**Comment by zivnevo** [comment]
> > ```
> > * [ ]  Is it possible to add some warning if there are gaps?
> > ```
> 
> Hi, As I saw, a warning will be printed to the log as the message of the creation of the artifact is printed. But ,although we don't have any performance issues currently and max factor (for tests other than git_resources, which I raised its expected runtime) was 2.3. In future we'll not be able to tell if there are performance issues unless we check manually the existence of the "failed_runtime_check" artifact, a thing that may be forgotten. So for example, shouldn't we increase the runtime_check factor up to 2.5 or 3 (instead of 2 ) and then to "stop/fail" the workflow run in case the failed_runtime_check artifact is created?

I suggest two thresholds: one for reporting in the artifact and (a bigger) one for making the test fail.
